trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm test
  displayName: 'Build and Test'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifact: 'drop'
  displayName: 'Publish Artifact'
  - stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployWeb
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              azureSubscription: '<your-azure-subscription>'
              appType: 'webAppLinux'
              appName: '<your-app-name>'
              package: '$(Pipeline.Workspace)/drop/*.zip'
              - task: Docker@2
  inputs:
    command: 'build'
    dockerfile: '**/Dockerfile'
    containerRegistry: '<your-container-registry>'
    repository: '<image-repo-name>'
    tags: |
      $(Build.BuildId)
      latest
