apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "pharmacy-logs-*"
    jsonData:
      esVersion: 7.10.0
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: log_level
    editable: true